# Generated by Django 4.0.6 on 2022-08-08 08:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='seria',
        ),
        migrations.AlterField(
            model_name='book',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 8, 11, 29, 6, 722308), editable=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 8, 11, 29, 6, 722308)),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='forecast.publisher'),
        ),
        migrations.AlterField(
            model_name='seria',
            name='publisher',
            field=models.ForeignKey(default='Unknown publisher', on_delete=django.db.models.deletion.CASCADE, to='forecast.publisher'),
        ),
    ]
