# Generated by Django 4.0.6 on 2022-07-10 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0002_genre_publisher_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='genre',
            field=models.CharField(choices=[('Nonfiction', (('Art/architecture', 'Art/architecture'), ('Autobiography', 'Autobiography'), ('Biography', 'Biography'), ('Business', 'Business/economics'), ('Crafts', 'Crafts/hobbies'), ('Cookbook', 'Cookbook'), ('Diary', 'Diary'), ('Dictionary', 'Dictionary'), ('Encyclopedia', 'Encyclopedia'), ('Guide', 'Guide'), ('Health', 'Health/fitness'), ('History', 'History'), ('Home', 'Home and garden'), ('Humor', 'Humor'), ('Journal', 'Journal'), ('MATH', 'Math'), ('Memoir', 'Memoir'), ('Philosophy', 'Philosophy'), ('Prayer', 'Prayer'), ('Religion', 'Religion, spirituality, and new age'), ('Textbook', 'Textbook'), ('True crime', 'True crime'), ('Review', 'Review'), ('Science', 'Science'), ('Self', 'Self help'), ('Sports', 'Sports and leisure'), ('Travel', 'Travel'), ('Other', 'Other'))), ('Fiction', (('Action', 'Action and adventure'), ('Alternate history', 'Alternate history'), ('Anthology', 'Anthology'), ('Chick lit', 'Chick lit'), ('Childrens', 'Childrens'), ('Classic', 'Classic'), ('Comic book', 'Comic book'), ('Coming-of-age', 'Coming-of-age'), ('Crime', 'Crime'), ('Drama', 'Drama'), ('Fairytale', 'Fairytale'), ('Fantasy', 'Fantasy'), ('Graphic novel', 'Graphic novel'), ('Historical fiction', 'Historical fiction'), ('Mystery', 'Horror'), ('Comic book', 'Mystery'), ('Paranormal romance', 'Paranormal romance'), ('Picture book', 'Picture book'), ('Poetry', 'Poetry'), ('Political thriller', 'Political thriller'), ('Romance', 'Romance'), ('Satire', 'Satire'), ('Science fiction', 'Science fiction'), ('Short story', 'Short story'), ('Suspense', 'Suspense'), ('Thriller', 'Thriller'), ('Thriller', 'Western'), ('Young adult', 'Young adult'), ('Other', 'Other'))), ('unknown', 'Unknown')], default='Other', max_length=20),
        ),
    ]
