# Generated by Django 4.0.6 on 2022-07-10 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0003_genre_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='bibliography',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forecast.book'),
        ),
        migrations.AlterField(
            model_name='series',
            name='puplisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forecast.publisher'),
        ),
    ]
