# Generated by Django 4.0.6 on 2022-07-24 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0003_bookinstance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='seria',
        ),
    ]
