# Generated by Django 4.0.6 on 2022-07-10 23:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0004_alter_author_bibliography_alter_series_puplisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='first_published',
            field=models.DateField(default=datetime.date(1990, 1, 1)),
        ),
    ]
