# Generated by Django 4.0.6 on 2022-08-21 23:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forecast', '0040_alter_book_created_alter_book_modified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created')),
                ('updated_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='updated')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cart', to=settings.AUTH_USER_MODEL, verbose_name='customer')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='John Doe', max_length=150)),
                ('telephone', models.CharField(default='+375-00-000-00-00', max_length=17)),
                ('address', models.CharField(default='somewhere', max_length=140)),
                ('desired_delivery_time', models.CharField(blank=True, choices=[('10am - 5pm', '10am - 5pm'), ('5pm - 10pm', '5pm - 10pm')], max_length=140)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='order.cart', verbose_name='Book in a Cart')),
            ],
        ),
        migrations.CreateModel(
            name='BookInCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_created=True, null=True, verbose_name='updated')),
                ('created_date', models.DateTimeField(auto_created=True, null=True, verbose_name='created')),
                ('quantity', models.SmallIntegerField(verbose_name='quantity')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='price')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods', to='forecast.book', verbose_name='Book')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods', to='order.cart', verbose_name='Book in a Cart')),
            ],
        ),
    ]
